apiVersion: apps/v1
kind: Deployment
metadata:
  name: peo-identity-api
  namespace: peo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peo-identity-api
  template:
    metadata:
      labels:
        app: peo-identity-api
    spec:
      containers:
        - name: peo-identity-api
          image: mba-projectfive-peo-identity-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__DefaultConnection
              value: "Data Source=../data/identity.db;"
            - name: ConnectionStrings__messaging
              value: "amqp://guest:guest@rabbitmq:5672"
          volumeMounts:
            - name: peo-data
              mountPath: /data          
      volumes:
        - name: peo-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: peo-identity-api
  namespace: peo
spec:
  selector:
    app: peo-identity-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
