apiVersion: v1
kind: ConfigMap
metadata:
  name: peo-faturamento-api-config
  namespace: peo
data:
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__DefaultConnection: Data Source=../data/faturamento.db;
---
apiVersion: v1
kind: Secret
metadata:
  name: peo-faturamento-api-secrets
  namespace: peo
type: Opaque
stringData:
  ConnectionStrings__messaging: amqp://guest:guest@rabbitmq:5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peo-faturamento-api
  namespace: peo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peo-faturamento-api
  template:
    metadata:
      labels:
        app: peo-faturamento-api
    spec:
      containers:
      - name: peo-faturamento-api
        image: mba-projectfive-peo-faturamento-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: peo-data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        envFrom:
        - configMapRef:
            name: peo-faturamento-api-config
        - secretRef:
            name: peo-faturamento-api-secrets
      volumes:
      - name: peo-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: peo-faturamento-api
  namespace: peo
spec:
  selector:
    app: peo-faturamento-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
