name: CI - Build, Test e SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Instalar SonarCloud Scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Adicionar scanner ao PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Iniciar análise SonarCloud (SOMENTE *Command.cs, EXCETO Command.cs)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"FilipeAlan_MBA-ProjectFive" \
            /o:"filipealan" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.inclusions="**/*Command.cs" \
            /d:sonar.exclusions="**/Command.cs" \
            /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml,**/TestResults/coverage.opencover.xml"

      - name: Restore
        run: dotnet restore

      - name: Build (Debug)
        run: dotnet build --configuration Debug --no-restore

      - name: Testes com cobertura 
        run: |
          dotnet test --configuration Debug --no-build \
            /p:CollectCoverage=true \
            /p:IncludeByFile="**/*Command.cs" \
            /p:ExcludeByFile="**/Command.cs" \
            /p:CoverletOutput=TestResults/coverage.opencover.xml \
            /p:CoverletOutputFormat=opencover

      - name: Finalizar análise SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
